//! Instrument 1 — parsing correctness.
//!
//! Settles: does the right text come out of each format. Fixtures are generated by
//! `scripts/make_fixtures.py`; the PDFs come from PyMuPDF, a different implementation
//! from the reader under test, so agreement here is between two independent codebases
//! rather than a round-trip through one.

use keyword_extraction_pipeline::{
    parse::{self, SourceKind},
    Config, FormatHint,
};

fn fixture(name: &str) -> Vec<u8> {
    let path = concat!(env!("CARGO_MANIFEST_DIR"), "/tests/fixtures/");
    std::fs::read(format!("{path}{name}"))
        .unwrap_or_else(|e| panic!("fixture {name}: {e}; run scripts/make_fixtures.py"))
}

fn parse_fixture(name: &str) -> parse::RawText {
    parse::parse(&fixture(name), FormatHint::Sniff, &Config::default())
        .unwrap_or_else(|e| panic!("parsing {name}: {e}"))
}

#[test]
fn pdf_yields_body_text_and_planted_identifiers() {
    let out = parse_fixture("simple.pdf");
    assert_eq!(out.source, SourceKind::Pdf);
    assert_eq!(out.text_layer_present, Some(true));

    for planted in ["DS-2291", "HEK293T", "SOP-114", "MabSelect SuRe"] {
        assert!(out.text.contains(planted), "missing {planted} in: {:?}", out.text);
    }
}

#[test]
fn two_column_pdf_does_not_interleave_columns() {
    // The failure this guards against is line-by-line interleaving of the two columns,
    // which splices unrelated sentences together and destroys phrase-level extraction.
    let out = parse_fixture("two_column.pdf");
    let text = out.text.replace('\n', " ");

    let left = text.find("left column").expect("left column text missing");
    let right = text.find("right column").expect("right column text missing");
    let culture = text.find("culture conditions").expect("right column tail missing");

    assert!(left < right, "columns read out of order: {text:?}");
    assert!(
        right < culture,
        "right column body was split away from its heading: {text:?}"
    );
}

#[test]
fn scanned_pdf_reports_no_text_layer_rather_than_looking_bland() {
    // The load-bearing case. An image-only PDF parses cleanly and extracts nothing;
    // without this signal it is indistinguishable from a document with no distinctive
    // content, and would be silently dropped from the corpus.
    let out = parse_fixture("scanned.pdf");
    assert_eq!(out.source, SourceKind::Pdf);
    assert_eq!(
        out.text_layer_present,
        Some(false),
        "scanned PDF must be flagged, got text: {:?}",
        out.text
    );
}

#[test]
fn docx_joins_runs_within_a_paragraph() {
    let out = parse_fixture("simple.docx");
    assert_eq!(out.source, SourceKind::WordProcessing);
    // "Batch ", "DS-2291", " was purified" are three separate runs in the XML. A reader
    // that inserts breaks between runs would split the identifier from its context.
    assert!(
        out.text.contains("Batch DS-2291 was purified"),
        "runs were not joined: {:?}",
        out.text
    );
    assert!(out.text.contains("HEK293T"));
}

#[test]
fn xlsx_keeps_string_cells_and_drops_bare_numerics() {
    let out = parse_fixture("simple.xlsx");
    assert_eq!(out.source, SourceKind::Spreadsheet);
    assert!(out.text.contains("DS-2291"), "got: {:?}", out.text);
    assert!(out.text.contains("Runs"), "sheet name missing: {:?}", out.text);
    assert!(
        !out.text.contains("91.4"),
        "bare numerics would flood the identifier lane: {:?}",
        out.text
    );
}

#[test]
fn pptx_reads_slide_text() {
    let out = parse_fixture("simple.pptx");
    assert_eq!(out.source, SourceKind::Presentation);
    assert!(out.text.contains("DS-2291"), "got: {:?}", out.text);
    assert!(out.text.contains("MabSelect SuRe"));
}

#[test]
fn email_takes_subject_and_body_but_not_message_id() {
    let out = parse_fixture("thread.eml");
    assert_eq!(out.source, SourceKind::Email);
    assert!(out.text.contains("DS-2291"));
    assert!(out.text.contains("regenerated per SOP-114"));
    assert!(
        !out.text.contains("QQ7F3K2M"),
        "message-id must not reach the lanes: {:?}",
        out.text
    );
}

#[test]
fn plain_text_passes_through() {
    let out = parse_fixture("simple.txt");
    assert_eq!(out.source, SourceKind::Plain);
    assert!(out.text.contains("DS-2291"));
}

#[test]
fn every_fixture_parses_without_error() {
    for name in [
        "simple.pdf", "two_column.pdf", "scanned.pdf", "simple.docx",
        "simple.xlsx", "simple.pptx", "thread.eml", "simple.txt",
    ] {
        parse_fixture(name);
    }
}
